services:
  - type: web
    name: flask-model-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --timeout 120 --bind 0.0.0.0:$PORT

    envVars:
      - key: PORT
        value: 10000
